name: Documentation Test

on:
  push:
    branches: 
      - pipeline
  pull_request:
    branches: [master]
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build
        uses: nidhigiridhar/cse110-w21-group35@v0.1
        with:
          source_dir: ./src
          output_dir: ./out
          config_file: conf.json
          template: minami
          front_page: doc.md

      - name: Deploy
        run: |
          jsdoc test.js