name: Documentation Test

on:
  push:
    branches: 
      - pipeline
  pull_request:
    branches: [master]
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build
        uses: nidhigiridhar/cse110-w21-group35@v0.1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./out
          config_file: conf.json
          template: minami
          front_page: doc.md
      
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_dir: ./out

      # - name: Deploy
      #   run: |
      #     npm install --save-dev jsdoc
      #     npm jsdoc test.js