name: Unit Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install
          npm test timer.test.js
          npm test notifications.test.js
          npm test notifications.showNotif.test.js
